### PR TITLE
Improvements regarding compiling on older MacOS versions.

### PR DESCRIPTION
**Pull request by motoo-tobbler**
I would like to address to you, that many MacOS users on the older versions of the system have been having issues playing the game, or issues while assembling the game. This aim of the pull request is to make the process easier for the said players.

## What limits the above mentioned players?

1. **Problems during compilation:**

    On the root level, the players who actively use older and/or outdated versions of MacOS may experience certain problems during the process of compilation, such as:

  - `gmake: cpp-9: No such file or directory` error
  - `Makefile.split:197: build/us_pc/level_rules.mk: No such file or directory` error

      _The latter is directly dependent on the former._

      These errors occur due to the absence of the dependency called `gcc@9` on the system belonging to the respective player.

2. **Problems post compilation:**

    Now that the players have compiled the game, they might wish to try the newly released CoopNet. However due to the current setup in the repository, it seemed that the players on the MacOS versions older than 10.15 experienced crashes related the libjuice library.

```
Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: */libjuice.1.2.2.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
```

## Solutions provided in this pull request

1. Two additional short sections have been added to the MacOS (Intel) Wiki, concerning the compilation on older MacOS versions, and the issue related to the libjuice library. My edition of the Wiki can be found [here](https://github.com/motoo-tobbler/sm64ex-coop/wiki/Compiling-on-MacOS-(Intel)). 

2.  A shell-script has been added to the repository. The shell-script compiles and copies the specified version of libjuice to the respective folder. And a minor change has been made regarding renaming the library from `libjuice.1.2.2.dylib` to `libjuice.dylib`

***

Accepting the pull request would greatly benefit MacOS users.

Thank you MysterD (djoslin0) for considering it, and giving me a chance.
Kindly look into the Wiki as well.

###### It took me a somewhat long time in order to find volunteers to test my additions locally. It has been a great experience adventuring through MacOS and its tools, and getting the solution to the public.

### CODE REVIEW

**Comment by EmeraldLoc** [comment]
dyld[27088]: Library not loaded: @rpath/libjuice.1.2.2.dylib
  Referenced from: <E90D6698-AF66-3A56-B298-C69AA1DA43F3> /Users/calebelm/test/build/us_pc/libcoopnet.dylib
  Reason: tried: './libjuice.1.2.2.dylib' (no such file), '/Users/calebelm/test/build/us_pc/libjuice.1.2.2.dylib' (no such file), './libjuice.1.2.2.dylib' (no such file), 'lib/discordsdk/libjuice.1.2.2.dylib' (no such file), 'lib/bass/libjuice.1.2.2.dylib' (no such file), '/Users/calebelm/test/build/us_pc/libjuice.1.2.2.dylib' (no such file), './libjuice.1.2.2.dylib' (no such file), 'lib/discordsdk/libjuice.1.2.2.dylib' (no such file), 'lib/bass/libjuice.1.2.2.dylib' (no such file), '/usr/local/lib/libjuice.1.2.2.dylib' (no such file), '/usr/lib/libjuice.1.2.2.dylib' (no such file, not in dyld cache)
[1]    27088 abort      ./build/us_pc/sm64.us.f3dex2e.app

Failed on macos ventura,tinkering with it, might know the issue

**Comment by EmeraldLoc** [comment]
The compilation issue was that the libjuice file was named "libjuice.1.2.2.dylib", renamed it to "libjuice.dylib", figuring out the runtime issue

**Comment by EmeraldLoc** [comment]
The issue here, after trying again and clearing my mind, is that the executable is looking for libjuice.1.2.2.dylib, but its name libjuice.dylib. I can't see why its looking for libjuice.1.2.2, but this isn't my pr, and other than this problem, pr looks good! If you have discord, make sure to talk to the devs about this pr, since you have to do some steps...

**Comment by motoo-tobbler** [comment]
> The issue here, after trying again and clearing my mind, is that the executable is looking for libjuice.1.2.2.dylib, but its name libjuice.dylib. I can't see why its looking for libjuice.1.2.2, but this isn't my pr, and other than this problem, pr looks good! If you have discord, make sure to talk to the devs about this pr, since you have to do some steps...

I have found out what really causes this problem. I looked through the strings of the libjuice library. The @rpath/libjuice.[version].dylib is hardcoded into the library. I am looking into it.

**Comment by motoo-tobbler** [comment]
For the time being, assuming that the version 1.2.2 of libjuice will be continued to be used, I have renamed `libjuice.dylib` back to `libjuice.1.2.2.dylib` (as it was before).

I'll admit that my focus was mainly on the root issue (i.e. compilation), with only some attention given to the libjuice library.

I apologize for any trouble I caused. Thank you for your patience and precious time.

**Pull request closed without merging**
