### PR TITLE
Refactor domain_resolution to reduce side effects

### PR DESCRIPTION
**Pull request by runleveldev**
These refactors remove the need for the global gGetHostName, which was being assigned as the entire string in the IP text box. This caused save_domain to put the full string (ip/hostname and port) back into configJoinIp, which made it so that when the config was saved, the IP string included the port number. This caused an annoying bug where reopening the game would cause the IP text box to look like it was appending the port twice. By removing the global and some of the side effects of domain_resolution, this bug is fixed.

### CODE REVIEW

**Comment by Isaac0-dev** [comment]
this bug has already been fixed for beta 31

**Comment by runleveldev** [comment]
Where can I find the beta?

**Comment by Isaac0-dev** [comment]
its not public yet. thats how we work on this project, we make updates privately, and then we release them later

**Comment by runleveldev** [comment]
I see, no need for this merge then if you have it handled.

**Pull request closed without merging**
