### PR TITLE
Fix Mario's Cap Texture Corruption

### PR DESCRIPTION
**Pull request by avereyishere**
When Ever A Mario Cap Gets Detached From Marios Head All The Textures Get Corrupted

### CODE REVIEW

**Comment by avereyishere** [comment]
image

**Comment by djoslin0** [comment]
Nice find, it also happens with Luigi's cap.
But we don't merge PRs in this repo (and this was fixed in the dev repo)
You can request access to it in the discord if you'd like.
v36.1 will come out toward the end of the weekend to try to fix all of the new bugs

**Comment by 12abz** [comment]
image

**Comment by avereyishere** [comment]
> Nice find, it also happens with Luigi's cap. But we don't merge PRs in this repo (and this was fixed in the dev repo) You can request access to it in the discord if you'd like. v36.1 will come out toward the end of the weekend to try to fix all of the new bugs

Oh I Didn't See That Message.

**Comment by avereyishere** [comment]
Discord Handle: theperfectmario64

**Comment by yoyeet961** [comment]
close this

**Comment by avereyishere** [comment]
Okay.

**Pull request closed without merging**
