### PR TITLE
Add custom cam mode

### PR DESCRIPTION
**Pull request by fgetcat**
Adds a camera mode which allows to change the position and focus point of the camera inside the lua script itself.
Example mod:
```
function custom_camera(pos, focus)
  m = gMarioStates[0]
  vec3f_set(pos, 0, 0, 0)
  vec3f_copy(focus, m.pos)
end

function mario_update_local(m)
  if (m.controller.buttonPressed & X_BUTTON) ~= 0 then 
    set_camera_mode(m.area.camera, CAMERA_MODE_CUSTOM, 1)
  end
end

function mario_update(m)
  if m.playerIndex == 0 then mario_update_local(m) end
end

hook_event(HOOK_MARIO_UPDATE, mario_update)
hook_event(HOOK_CUSTOM_CAMERA, custom_camera)
```

### CODE REVIEW

**Comment by Isaac0-dev** [comment]
you can write whole camera modes as Lua mods, so this isn't needed

**Comment by fgetcat** [comment]
> you can write whole camera modes as Lua mods, so this isn't needed

I think this solution is a bit cleaner and easier to use though.

**Comment by Isaac0-dev** [comment]
Lua mods can make any sort of camera mode they choose, while using your camera mode is limited to how you made it
also it looks like you've manually edited files that are usually generated automatically

**Comment by fgetcat** [comment]
> Lua mods can make any sort of camera mode they choose, while using your camera mode is limited to how you made it also it looks like you've manually edited files that are usually generated automatically

Can you provide a Lua mod example that does the exact same thing as the example above? Without the added features in my fork of course.

**Comment by fgetcat** [comment]
I discovered `camera_freeze()` and `camera_unfreeze()` functions which disable camera updates. The `gLakituState` can then be used to set the position and focus with the `pos` and `focus` properties respectively. I am now closing this pull request.

**Pull request closed without merging**
