### PR TITLE
Fix incorrect pitches in Mario's voicebank

### PR DESCRIPTION
**Pull request by dopadream**
It's incorrect

### CODE REVIEW

**Comment by AgentXLP** [comment]
?

**Comment by dopadream** [comment]
The pitches of Mario's voice dont match the recordings, and it was fixed in
the Shindou version of the game and onwards.

**Comment by Isaac0-dev** [comment]
they sound fine to me

**Comment by dopadream** [comment]
Oh. I guess it's subjective. It's technically a fix, but if you prefer the
transposed vocals I guess that's your call.

**Comment by AgentXLP** [comment]
We're trying to keep at least the singleplayer sm64ex-coop (which compiles with VERSION_US currently) experience accurate to vanilla, and in the US version these sounds do not need any change.

**Pull request closed without merging**
